language: node_js

node_js:
  -node

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm run start
  - npm run build
  - npm run test
  - npm run lint
  - npm run e2e
  - npm run aot
  - npm run aot